services:
  idp:
    build:
      context: ./idp
    image: idp-local
    environment:
      IDP_HTTP_ADDR: ":8080"
      IDP_ISSUER: "http://idp:8080"
      IDP_USERS_PATH: data/users.json
      IDP_CLIENTS_PATH: data/clients.json
    volumes:
      - ./idp/data:/app/data:ro
    expose:
      - "8080"
    networks:
      - idp_net

  bff:
    build:
      context: ./bff
    image: bff-local
    working_dir: /app
    depends_on:
      - idp
    command: sh -c "pnpm install && HOSTNAME=0.0.0.0 PORT=3000 pnpm dev"
    environment:
      NODE_ENV: development
      OIDC_ISSUER_URL: http://idp:8080
      OIDC_CLIENT_ID: web-app
      OIDC_CLIENT_SECRET: web-secret
      BFF_SESSION_SECRET: dev-secret-change-me
      BFF_TRUST_PROXY_HEADERS: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./bff:/app
      - node_modules_bff:/app/node_modules
    networks:
      - idp_net
      - web_net

  third:
    build:
      context: ./third
    image: third-local
    working_dir: /app
    depends_on:
      - bff
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    environment:
      NODE_ENV: development
      PORT: 4000
      BFF_PUBLIC_URL: http://localhost:3000
      BFF_API_BASE_URL: http://bff:3000
      OIDC_CLIENT_ID: third-web-app
      OIDC_CLIENT_SECRET: third-secret
      OIDC_REDIRECT_URI: http://localhost:4000/auth/callback
      OIDC_SCOPES: openid profile email
      THIRD_SESSION_SECRET: third-session-secret-change-me
      THIRD_SESSION_COOKIE_SECURE: "false"
    ports:
      - "4000:4000"
    volumes:
      - ./third:/app
      - node_modules_third:/app/node_modules
    networks:
      - web_net

volumes:
  node_modules_bff:
  node_modules_third:

networks:
  idp_net:
    internal: true
  web_net:
    driver: bridge
